#!/bin/bash
# This runs in Crontab to check that the wifi is working.  If it is faulty it will 
# firstly restart wifi and check all is running well.  If not, the script will reboot the PI
# Any checks and reboots are stored as actions in txt files in /home/pi/DomCode
# Dominic 29/1/2020

# Lines below are to get the date and time variables ready
BASHDATE=`date +"%b %d, %Y"`
BASHTIME=`date +" %T"`
# Start of code
ping -c1 10.3.1.1 > /dev/null
if [ $? != 0 ] 
then
#	Ping failed so  check, reset and reboot if necessary
	echo Ping test failed, restarting WiFi on ${BASHDATE} at: ${BASHTIME} >> /home/pi/wifi-reboot-log
	sudo ifconfig wlan0 down
	sleep 5
#	Restarting WIFI
	sudo ifconfig wlan0 up
	sleep 20
#	Re-ping after wifi re-start	
	ping -c1 10.3.1.1 > /dev/null
#	If Ping fails, reboot computer
	if [ $? != 0 ]
	then
		echo Post-WiFi restart ping test failed, reboot computer on ${BASHDATE} at: ${BASHTIME} >> /home/pi/wifi-reboot-log
		sleep 5
		sudo reboot
	fi

else
# If ping test succeeds, update log
	echo Ping test success on ${BASHDATE} at:  ${BASHTIME} > /home/pi/wifi-reboot-log
fi